name: Gather data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  gather-data:
    permissions:                # Job-level permissions configuration starts here
      contents: write           # 'write' access to repository contents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip" # caching pip dependencies
      - name: Install requirements.txt
        run: pip install -r requirements.txt
      - name: Gather data
        run: python main.py
      - name: Commit report
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "Automated report"
          git push
